### ISSUE TITLE
Exception when deserializing an entity with empty to-one relationship

### ISSUE THREAD

**Issue by JesperTreetop** [cosullivan/Hypermedia#10]
When Hypermedia attempts to deserialize a relationship with an empty to-one relationship (ie `"relationships": { "person": { "data": null } }`), it crashes in `DeserializeRelationships` [on this line](https://github.com/cosullivan/Hypermedia/blob/751a0be8a9d58400ea067cb9ff051bf11fd5f0b1/Src/Hypermedia.JsonApi/JsonApiSerializer.cs#L1063) because `data` is being cast to `JsonObject` when it is `JsonNull`.

**Comment by cosullivan** [comment]
Hi,

Thanks for raising that. I have just pushed out a new package with a fix for this issue.

Thanks,
Cain.
