### ISSUE TITLE
Example for PostAsync

### ISSUE THREAD

**Issue by Afshin1980** [cosullivan/Hypermedia#11]
Hello 
i use hypermedia in Xamarin form and i am looking for a sample for using PostAsync method but i couldn't find it in your sample project .is it possible to give me an example for using PostAsync method for sending data to server.

**Comment by cosullivan** [comment]
Hi,

I just added this to the samples, have a look at this commit;
https://github.com/cosullivan/Hypermedia/commit/90fc4e5c35dbec2d410c4761c50f13d94247fb1c

Thanks,
Cain.

**Comment by Afshin1980** [comment]
Thank you for your response
i use your sample for PostAsync and i get "415 unsupported media type"  error but when i use GetAsync i can get the data from server

**Comment by cosullivan** [comment]
Hi,

Are you connecting to a Web API server, or some other server? If you are using Web API, can you make sure you have the JsonApi formatter configured?

https://github.com/cosullivan/Hypermedia/blob/master/Src/Hypermedia.Sample.WebApi/App_Start/WebApiConfig.cs#L46

Thanks,
Cain.
