### ISSUE TITLE
How to add metadata section?

### ISSUE THREAD

**Issue by ghost** [cosullivan/Hypermedia#13]

**Comment by ryab777** [comment]
Ok, I can add metadata such as time and version. I make pagination now. How I add the total number of records to metadata? There is method of GetPostsController in Hypermedia.Sample.WebApi project:
`[HttpGet, Route("v1/posts")]
        public IHttpActionResult Execute(string q = null, int skip = 0, int take = 100, IRequestMetadata<PostResource> metadata = null)
        {
            var posts = _database.Posts.GetAll(Predicate(q), skip, take).AsResource();

            foreach (var post in posts)
            {
                post.Populate(_database);
            }

            return Ok(posts);
        }`
Can you show me how add the total number of records to metadata on this example?
Thank you.

**Comment by cosullivan** [comment]
Hi,

There is no easy way to attach metadata to the request, but I would suggest the easist way is to attach your own properties to the Request message (ie, Request.Properties.Add(...) from within the controller) and then read these out during the media type formatting stage.

The key here is to take note of the "GetPerRequestFormatterInstance" method that gets called on the formatter as this has the request message passed to it.

Thanks,
Cain.
