### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by m-nagy** [cosullivan/Hypermedia#2]
I tried the formatter with non-Latin characters and it serialize it as '????'

**Comment by cosullivan** [comment]
Hi, can you please provide a bit more information? 

Are you serializing an object that has a string property which contains non-Latin characters?

**Comment by m-nagy** [comment]
Yes

**Comment by cosullivan** [comment]
Can you try installing version 1.3.0 which I just published to Nuget. This now has Unicode support.

Thanks.
Cain

**Comment by m-nagy** [comment]
It works, Thank you
