### ISSUE TITLE
Support for Errors

### ISSUE THREAD

**Issue by wardsa013** [cosullivan/Hypermedia#5]
Would be great if support for serializing errors ([http://jsonapi.org/format/#error-objects](url)) was available.

Unless they are already implemented and I'm overlooking them.

**Comment by cosullivan** [comment]
Hi, no they are not currently supported. I have looked into it in the past and it is on the TODO list. I might revisit this soon.

**Comment by wardsa013** [comment]
This is the workaround I ended up writing. Leaving it here in case it could help anybody else until this support gets officially added. Basically all it does is attempt to serialize instances of HttpError prior to running the serialization from this framework.

[Gist with source.](https://gist.github.com/wardsa013/cea062f8a65e01018e2becaa91b7a801)

You just need to use JsonApiMediaTypeFormatterWithErrorSupport instead of the JsonApiMediaTypeFormatter.

**Comment by cosullivan** [comment]
FYI,

I've just pushed a release that now has support for errors. Would be good to get your feedback.

Thanks,
Cain
